#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# fish like suggestions
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# emacs
export ALTERNATE_EDITOR="vim"
# export EDITOR="emacsclient -t"                  # $EDITOR opens in terminal
# export VISUAL="emacsclient -c -a emacs"         # $VISUAL opens in GUI mode
# alias emacs='emacsclient -create-frame'
# alias vim='emacsclient -t'

PATH=$PATH:~/.scripts

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/tim/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/tim/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/tim/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/tim/Downloads/google-cloud-sdk/completion.zsh.inc'; fi
